/* eslint-disable @typescript-eslint/no-explicit-any */
/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API
 * API documentation for the starter-kit project in NestJS by BinarApps. The API allows management of users, sessions and offers various functions for logged in users. Contains examples of authentication, authorization, and CRUD for selected resources.
 * OpenAPI spec version: 1.0
 */
import { useMutation, useQuery } from '@tanstack/react-query'
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query'

import { customInstance } from '../../axios/custom-instance'
import type { ErrorType, BodyType } from '../../axios/custom-instance'
import type {
  ArticleEntity,
  ArticlesControllerFindAllParams,
  ArticlesControllerFindDraftsParams,
  CreateArticleDto,
  ErrorServerEntity,
  ErrorValidationEntity,
  UpdateArticleDto,
} from '../../types'

type SecondParameter<T extends (...args: any) => any> = Parameters<T>[1]

/**
 * Creates a new article with the provided details.
 * @summary Create Article
 */
export const articlesControllerCreate = (
  createArticleDto: BodyType<CreateArticleDto>,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal
) => {
  return customInstance<ArticleEntity>(
    {
      url: `/api/v1/articles`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: createArticleDto,
      signal,
    },
    options
  )
}

export const getArticlesControllerCreateMutationOptions = <
  TData = Awaited<ReturnType<typeof articlesControllerCreate>>,
  TError = ErrorType<ErrorValidationEntity | ErrorServerEntity>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<TData, TError, { data: BodyType<CreateArticleDto> }, TContext>
  request?: SecondParameter<typeof customInstance>
}) => {
  const mutationKey = ['articlesControllerCreate']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof articlesControllerCreate>>,
    { data: BodyType<CreateArticleDto> }
  > = (props) => {
    const { data } = props ?? {}

    return articlesControllerCreate(data, requestOptions)
  }

  return { mutationFn, ...mutationOptions } as UseMutationOptions<
    TData,
    TError,
    { data: BodyType<CreateArticleDto> },
    TContext
  >
}

export type ArticlesControllerCreateMutationResult = NonNullable<
  Awaited<ReturnType<typeof articlesControllerCreate>>
>
export type ArticlesControllerCreateMutationBody = BodyType<CreateArticleDto>
export type ArticlesControllerCreateMutationError = ErrorType<
  ErrorValidationEntity | ErrorServerEntity
>

/**
 * @summary Create Article
 */
export const useArticlesControllerCreate = <
  TData = Awaited<ReturnType<typeof articlesControllerCreate>>,
  TError = ErrorType<ErrorValidationEntity | ErrorServerEntity>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<TData, TError, { data: BodyType<CreateArticleDto> }, TContext>
  request?: SecondParameter<typeof customInstance>
}): UseMutationResult<TData, TError, { data: BodyType<CreateArticleDto> }, TContext> => {
  const mutationOptions = getArticlesControllerCreateMutationOptions(options)

  return useMutation(mutationOptions)
}
/**
 * Retrieves a list of all articles with pagination support.
 * @summary Find All Articles
 */
export const articlesControllerFindAll = (
  params: ArticlesControllerFindAllParams,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal
) => {
  return customInstance<ArticleEntity[]>(
    { url: `/api/v1/articles`, method: 'GET', params, signal },
    options
  )
}

export const getArticlesControllerFindAllQueryKey = (params: ArticlesControllerFindAllParams) => {
  return [`/api/v1/articles`, ...(params ? [params] : [])] as const
}

export const getArticlesControllerFindAllQueryOptions = <
  TData = Awaited<ReturnType<typeof articlesControllerFindAll>>,
  TError = ErrorType<ErrorServerEntity>,
>(
  params: ArticlesControllerFindAllParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof articlesControllerFindAll>>, TError, TData>
    >
    request?: SecondParameter<typeof customInstance>
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getArticlesControllerFindAllQueryKey(params)

  const queryFn: QueryFunction<Awaited<ReturnType<typeof articlesControllerFindAll>>> = ({
    signal,
  }) => articlesControllerFindAll(params, requestOptions, signal)

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof articlesControllerFindAll>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ArticlesControllerFindAllQueryResult = NonNullable<
  Awaited<ReturnType<typeof articlesControllerFindAll>>
>
export type ArticlesControllerFindAllQueryError = ErrorType<ErrorServerEntity>

export function useArticlesControllerFindAll<
  TData = Awaited<ReturnType<typeof articlesControllerFindAll>>,
  TError = ErrorType<ErrorServerEntity>,
>(
  params: ArticlesControllerFindAllParams,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof articlesControllerFindAll>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof articlesControllerFindAll>>,
          TError,
          TData
        >,
        'initialData'
      >
    request?: SecondParameter<typeof customInstance>
  }
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useArticlesControllerFindAll<
  TData = Awaited<ReturnType<typeof articlesControllerFindAll>>,
  TError = ErrorType<ErrorServerEntity>,
>(
  params: ArticlesControllerFindAllParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof articlesControllerFindAll>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof articlesControllerFindAll>>,
          TError,
          TData
        >,
        'initialData'
      >
    request?: SecondParameter<typeof customInstance>
  }
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useArticlesControllerFindAll<
  TData = Awaited<ReturnType<typeof articlesControllerFindAll>>,
  TError = ErrorType<ErrorServerEntity>,
>(
  params: ArticlesControllerFindAllParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof articlesControllerFindAll>>, TError, TData>
    >
    request?: SecondParameter<typeof customInstance>
  }
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Find All Articles
 */

export function useArticlesControllerFindAll<
  TData = Awaited<ReturnType<typeof articlesControllerFindAll>>,
  TError = ErrorType<ErrorServerEntity>,
>(
  params: ArticlesControllerFindAllParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof articlesControllerFindAll>>, TError, TData>
    >
    request?: SecondParameter<typeof customInstance>
  }
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getArticlesControllerFindAllQueryOptions(params, options)

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
  }

  query.queryKey = queryOptions.queryKey

  return query
}

/**
 * Retrieves a list of draft articles with pagination support.
 * @summary Find Draft Articles
 */
export const articlesControllerFindDrafts = (
  params: ArticlesControllerFindDraftsParams,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal
) => {
  return customInstance<ArticleEntity[]>(
    { url: `/api/v1/articles/drafts`, method: 'GET', params, signal },
    options
  )
}

export const getArticlesControllerFindDraftsQueryKey = (
  params: ArticlesControllerFindDraftsParams
) => {
  return [`/api/v1/articles/drafts`, ...(params ? [params] : [])] as const
}

export const getArticlesControllerFindDraftsQueryOptions = <
  TData = Awaited<ReturnType<typeof articlesControllerFindDrafts>>,
  TError = ErrorType<ErrorServerEntity>,
>(
  params: ArticlesControllerFindDraftsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof articlesControllerFindDrafts>>, TError, TData>
    >
    request?: SecondParameter<typeof customInstance>
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getArticlesControllerFindDraftsQueryKey(params)

  const queryFn: QueryFunction<Awaited<ReturnType<typeof articlesControllerFindDrafts>>> = ({
    signal,
  }) => articlesControllerFindDrafts(params, requestOptions, signal)

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof articlesControllerFindDrafts>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ArticlesControllerFindDraftsQueryResult = NonNullable<
  Awaited<ReturnType<typeof articlesControllerFindDrafts>>
>
export type ArticlesControllerFindDraftsQueryError = ErrorType<ErrorServerEntity>

export function useArticlesControllerFindDrafts<
  TData = Awaited<ReturnType<typeof articlesControllerFindDrafts>>,
  TError = ErrorType<ErrorServerEntity>,
>(
  params: ArticlesControllerFindDraftsParams,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof articlesControllerFindDrafts>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof articlesControllerFindDrafts>>,
          TError,
          TData
        >,
        'initialData'
      >
    request?: SecondParameter<typeof customInstance>
  }
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useArticlesControllerFindDrafts<
  TData = Awaited<ReturnType<typeof articlesControllerFindDrafts>>,
  TError = ErrorType<ErrorServerEntity>,
>(
  params: ArticlesControllerFindDraftsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof articlesControllerFindDrafts>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof articlesControllerFindDrafts>>,
          TError,
          TData
        >,
        'initialData'
      >
    request?: SecondParameter<typeof customInstance>
  }
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useArticlesControllerFindDrafts<
  TData = Awaited<ReturnType<typeof articlesControllerFindDrafts>>,
  TError = ErrorType<ErrorServerEntity>,
>(
  params: ArticlesControllerFindDraftsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof articlesControllerFindDrafts>>, TError, TData>
    >
    request?: SecondParameter<typeof customInstance>
  }
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Find Draft Articles
 */

export function useArticlesControllerFindDrafts<
  TData = Awaited<ReturnType<typeof articlesControllerFindDrafts>>,
  TError = ErrorType<ErrorServerEntity>,
>(
  params: ArticlesControllerFindDraftsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof articlesControllerFindDrafts>>, TError, TData>
    >
    request?: SecondParameter<typeof customInstance>
  }
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getArticlesControllerFindDraftsQueryOptions(params, options)

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
  }

  query.queryKey = queryOptions.queryKey

  return query
}

/**
 * Retrieves an article by its unique identifier.
 * @summary Find Article by ID
 */
export const articlesControllerFindOne = (
  id: number,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal
) => {
  return customInstance<ArticleEntity>(
    { url: `/api/v1/articles/${id}`, method: 'GET', signal },
    options
  )
}

export const getArticlesControllerFindOneQueryKey = (id: number) => {
  return [`/api/v1/articles/${id}`] as const
}

export const getArticlesControllerFindOneQueryOptions = <
  TData = Awaited<ReturnType<typeof articlesControllerFindOne>>,
  TError = ErrorType<ErrorServerEntity>,
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof articlesControllerFindOne>>, TError, TData>
    >
    request?: SecondParameter<typeof customInstance>
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getArticlesControllerFindOneQueryKey(id)

  const queryFn: QueryFunction<Awaited<ReturnType<typeof articlesControllerFindOne>>> = ({
    signal,
  }) => articlesControllerFindOne(id, requestOptions, signal)

  return { queryKey, queryFn, enabled: !!id, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof articlesControllerFindOne>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ArticlesControllerFindOneQueryResult = NonNullable<
  Awaited<ReturnType<typeof articlesControllerFindOne>>
>
export type ArticlesControllerFindOneQueryError = ErrorType<ErrorServerEntity>

export function useArticlesControllerFindOne<
  TData = Awaited<ReturnType<typeof articlesControllerFindOne>>,
  TError = ErrorType<ErrorServerEntity>,
>(
  id: number,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof articlesControllerFindOne>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof articlesControllerFindOne>>,
          TError,
          TData
        >,
        'initialData'
      >
    request?: SecondParameter<typeof customInstance>
  }
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useArticlesControllerFindOne<
  TData = Awaited<ReturnType<typeof articlesControllerFindOne>>,
  TError = ErrorType<ErrorServerEntity>,
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof articlesControllerFindOne>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof articlesControllerFindOne>>,
          TError,
          TData
        >,
        'initialData'
      >
    request?: SecondParameter<typeof customInstance>
  }
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useArticlesControllerFindOne<
  TData = Awaited<ReturnType<typeof articlesControllerFindOne>>,
  TError = ErrorType<ErrorServerEntity>,
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof articlesControllerFindOne>>, TError, TData>
    >
    request?: SecondParameter<typeof customInstance>
  }
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Find Article by ID
 */

export function useArticlesControllerFindOne<
  TData = Awaited<ReturnType<typeof articlesControllerFindOne>>,
  TError = ErrorType<ErrorServerEntity>,
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof articlesControllerFindOne>>, TError, TData>
    >
    request?: SecondParameter<typeof customInstance>
  }
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getArticlesControllerFindOneQueryOptions(id, options)

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
  }

  query.queryKey = queryOptions.queryKey

  return query
}

/**
 * Updates an article with the provided details.
 * @summary Update Article
 */
export const articlesControllerUpdate = (
  id: number,
  updateArticleDto: BodyType<UpdateArticleDto>,
  options?: SecondParameter<typeof customInstance>
) => {
  return customInstance<ArticleEntity>(
    {
      url: `/api/v1/articles/${id}`,
      method: 'PATCH',
      headers: { 'Content-Type': 'application/json' },
      data: updateArticleDto,
    },
    options
  )
}

export const getArticlesControllerUpdateMutationOptions = <
  TData = Awaited<ReturnType<typeof articlesControllerUpdate>>,
  TError = ErrorType<ErrorValidationEntity | ErrorServerEntity>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    TData,
    TError,
    { id: number; data: BodyType<UpdateArticleDto> },
    TContext
  >
  request?: SecondParameter<typeof customInstance>
}) => {
  const mutationKey = ['articlesControllerUpdate']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof articlesControllerUpdate>>,
    { id: number; data: BodyType<UpdateArticleDto> }
  > = (props) => {
    const { id, data } = props ?? {}

    return articlesControllerUpdate(id, data, requestOptions)
  }

  return { mutationFn, ...mutationOptions } as UseMutationOptions<
    TData,
    TError,
    { id: number; data: BodyType<UpdateArticleDto> },
    TContext
  >
}

export type ArticlesControllerUpdateMutationResult = NonNullable<
  Awaited<ReturnType<typeof articlesControllerUpdate>>
>
export type ArticlesControllerUpdateMutationBody = BodyType<UpdateArticleDto>
export type ArticlesControllerUpdateMutationError = ErrorType<
  ErrorValidationEntity | ErrorServerEntity
>

/**
 * @summary Update Article
 */
export const useArticlesControllerUpdate = <
  TData = Awaited<ReturnType<typeof articlesControllerUpdate>>,
  TError = ErrorType<ErrorValidationEntity | ErrorServerEntity>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    TData,
    TError,
    { id: number; data: BodyType<UpdateArticleDto> },
    TContext
  >
  request?: SecondParameter<typeof customInstance>
}): UseMutationResult<
  TData,
  TError,
  { id: number; data: BodyType<UpdateArticleDto> },
  TContext
> => {
  const mutationOptions = getArticlesControllerUpdateMutationOptions(options)

  return useMutation(mutationOptions)
}
/**
 * Deletes an article by its unique identifier.
 * @summary Remove Article
 */
export const articlesControllerRemove = (
  id: number,
  options?: SecondParameter<typeof customInstance>
) => {
  return customInstance<void>({ url: `/api/v1/articles/${id}`, method: 'DELETE' }, options)
}

export const getArticlesControllerRemoveMutationOptions = <
  TData = Awaited<ReturnType<typeof articlesControllerRemove>>,
  TError = ErrorType<ErrorServerEntity>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<TData, TError, { id: number }, TContext>
  request?: SecondParameter<typeof customInstance>
}) => {
  const mutationKey = ['articlesControllerRemove']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof articlesControllerRemove>>,
    { id: number }
  > = (props) => {
    const { id } = props ?? {}

    return articlesControllerRemove(id, requestOptions)
  }

  return { mutationFn, ...mutationOptions } as UseMutationOptions<
    TData,
    TError,
    { id: number },
    TContext
  >
}

export type ArticlesControllerRemoveMutationResult = NonNullable<
  Awaited<ReturnType<typeof articlesControllerRemove>>
>

export type ArticlesControllerRemoveMutationError = ErrorType<ErrorServerEntity>

/**
 * @summary Remove Article
 */
export const useArticlesControllerRemove = <
  TData = Awaited<ReturnType<typeof articlesControllerRemove>>,
  TError = ErrorType<ErrorServerEntity>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<TData, TError, { id: number }, TContext>
  request?: SecondParameter<typeof customInstance>
}): UseMutationResult<TData, TError, { id: number }, TContext> => {
  const mutationOptions = getArticlesControllerRemoveMutationOptions(options)

  return useMutation(mutationOptions)
}
