/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API
 * API documentation for the starter-kit project in NestJS by BinarApps. The API allows management of users, sessions and offers various functions for logged in users. Contains examples of authentication, authorization, and CRUD for selected resources.
 * OpenAPI spec version: 1.0
 */
import type { AuthorPublicDto } from './authorPublicDto'

export interface ArticleEntity {
  id: number
  title: string
  /** @nullable */
  description?: string | null
  body: string
  published: boolean
  createdAt: string
  updatedAt: string
  deletedAt: string
  /** @nullable */
  authorId?: string | null
  author: AuthorPublicDto
}
