/* eslint-disable @typescript-eslint/no-explicit-any */
/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API
 * API documentation for the starter-kit project in NestJS by BinarApps. The API allows management of users, sessions and offers various functions for logged in users. Contains examples of authentication, authorization, and CRUD for selected resources.
 * OpenAPI spec version: 1.0
 */

export interface AuthRegisterLoginDto {
  email: string
  firstName: string
  lastName: string
  /** IETF language tags (e.g., en-US). */
  locale: string
  password: string
  privacyPolicyAccepted: boolean
  termsAccepted: boolean
}
