/* eslint-disable @typescript-eslint/no-explicit-any */
/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API
 * API documentation for the starter-kit project in NestJS by BinarApps. The API allows management of users, sessions and offers various functions for logged in users. Contains examples of authentication, authorization, and CRUD for selected resources.
 * OpenAPI spec version: 1.0
 */

export interface AuthAppleLoginDto {
  /** The first name of the user. This field is optional and can be provided by Apple during the first sign-in. */
  firstName?: string
  /** The identity token issued by Apple, encoded in JWT format. */
  idToken: string
  /** The last name of the user. This field is optional and can be provided by Apple during the first sign-in. */
  lastName?: string
}
