/* eslint-disable @typescript-eslint/no-explicit-any */
/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API
 * API documentation for the starter-kit project in NestJS by BinarApps. The API allows management of users, sessions and offers various functions for logged in users. Contains examples of authentication, authorization, and CRUD for selected resources.
 * OpenAPI spec version: 1.0
 */

/**
 * The operating system for which to check the update. Can be either "android" or "ios".
 */
export type CheckUpdateDtoOs = (typeof CheckUpdateDtoOs)[keyof typeof CheckUpdateDtoOs]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CheckUpdateDtoOs = {
  android: 'android',
  ios: 'ios',
} as const
