/* eslint-disable @typescript-eslint/no-explicit-any */
/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API
 * API documentation for the starter-kit project in NestJS by BinarApps. The API allows management of users, sessions and offers various functions for logged in users. Contains examples of authentication, authorization, and CRUD for selected resources.
 * OpenAPI spec version: 1.0
 */

export interface FileEntity {
  /**
   * Category of the file
   * @nullable
   */
  category: string | null
  /** Creation date of the file */
  createdAt: string
  /** Unique identifier of the file */
  id: string
  /** MIME type of the file */
  mimeType: string
  /** Name of the file */
  name: string
  /** Path to access the file */
  path: string
  /** Size of the file in bytes */
  size: number
  /** Identifier of the user who owns the file */
  userId: string
}
