/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API
 * API documentation for the starter-kit project in NestJS by BinarApps. The API allows management of users, sessions and offers various functions for logged in users. Contains examples of authentication, authorization, and CRUD for selected resources.
 * OpenAPI spec version: 1.0
 */
import type { HealthCheckStatusDto } from './healthCheckStatusDto'

export interface HealthCheckInfoDto {
  /** The status of the database connection */
  db: HealthCheckStatusDto
  /** The status of the domain */
  domain: HealthCheckStatusDto
  /** The status of the cache */
  cache: HealthCheckStatusDto
}
