/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API
 * API documentation for the starter-kit project in NestJS by BinarApps. The API allows management of users, sessions and offers various functions for logged in users. Contains examples of authentication, authorization, and CRUD for selected resources.
 * OpenAPI spec version: 1.0
 */
import type { HealthCheckInfoDto } from './healthCheckInfoDto'
import type { HealthEntityError } from './healthEntityError'

export interface HealthEntity {
  /** Overall health status */
  status: string
  /** Detailed info about each component's health */
  info: HealthCheckInfoDto
  /** Details of any errors encountered during the health check */
  error: HealthEntityError
  /** Detailed health check results for each component */
  details: HealthCheckInfoDto
}
