/* eslint-disable @typescript-eslint/no-explicit-any */
/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API
 * API documentation for the starter-kit project in NestJS by BinarApps. The API allows management of users, sessions and offers various functions for logged in users. Contains examples of authentication, authorization, and CRUD for selected resources.
 * OpenAPI spec version: 1.0
 */

/**
 * Role ID, where 1 is for User and 2 is for Admin
 */
export type RoleId = (typeof RoleId)[keyof typeof RoleId]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RoleId = {
  NUMBER_1: 1,
  NUMBER_2: 2,
} as const
