/* eslint-disable @typescript-eslint/no-explicit-any */
/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API
 * API documentation for the starter-kit project in NestJS by BinarApps. The API allows management of users, sessions and offers various functions for logged in users. Contains examples of authentication, authorization, and CRUD for selected resources.
 * OpenAPI spec version: 1.0
 */
import type { LastConsentEntity } from './lastConsentEntity'
import type { Role } from './role'
import type { Status } from './status'

export interface UserEntity {
  consent?: LastConsentEntity
  createdAt: string
  deletedAt: string
  email: string
  firstName: string
  id: string
  lastName: string
  locale: string
  provider: string
  role: Role
  socialId: string
  status: Status
  updatedAt: string
}
