/* eslint-disable @typescript-eslint/no-explicit-any */
/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API
 * API documentation for the starter-kit project in NestJS by BinarApps. The API allows management of users, sessions and offers various functions for logged in users. Contains examples of authentication, authorization, and CRUD for selected resources.
 * OpenAPI spec version: 1.0
 */
import { useMutation, useQuery } from '@tanstack/react-query'
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query'

import { customInstance } from '../../axios/custom-instance'
import type { ErrorType, BodyType } from '../../axios/custom-instance'
import type { FileEntity, FilesControllerUploadFileBody } from '../../types'

type SecondParameter<T extends (...args: any) => any> = Parameters<T>[1]

/**
 * Uploads a file with a specified category.
 * @summary Upload File
 */
export const filesControllerUploadFile = (
  filesControllerUploadFileBody: BodyType<FilesControllerUploadFileBody>,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal
) => {
  const formData = new FormData()
  if (filesControllerUploadFileBody.file !== undefined) {
    formData.append('file', filesControllerUploadFileBody.file)
  }
  if (filesControllerUploadFileBody.category !== undefined) {
    formData.append('category', filesControllerUploadFileBody.category)
  }

  return customInstance<FileEntity>(
    {
      url: `/api/v1/files/upload`,
      method: 'POST',
      headers: { 'Content-Type': 'multipart/form-data' },
      data: formData,
      signal,
    },
    options
  )
}

export const getFilesControllerUploadFileMutationOptions = <
  TData = Awaited<ReturnType<typeof filesControllerUploadFile>>,
  TError = ErrorType<void>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    TData,
    TError,
    { data: BodyType<FilesControllerUploadFileBody> },
    TContext
  >
  request?: SecondParameter<typeof customInstance>
}) => {
  const mutationKey = ['filesControllerUploadFile']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof filesControllerUploadFile>>,
    { data: BodyType<FilesControllerUploadFileBody> }
  > = (props) => {
    const { data } = props ?? {}

    return filesControllerUploadFile(data, requestOptions)
  }

  return { mutationFn, ...mutationOptions } as UseMutationOptions<
    TData,
    TError,
    { data: BodyType<FilesControllerUploadFileBody> },
    TContext
  >
}

export type FilesControllerUploadFileMutationResult = NonNullable<
  Awaited<ReturnType<typeof filesControllerUploadFile>>
>
export type FilesControllerUploadFileMutationBody = BodyType<FilesControllerUploadFileBody>
export type FilesControllerUploadFileMutationError = ErrorType<void>

/**
 * @summary Upload File
 */
export const useFilesControllerUploadFile = <
  TData = Awaited<ReturnType<typeof filesControllerUploadFile>>,
  TError = ErrorType<void>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    TData,
    TError,
    { data: BodyType<FilesControllerUploadFileBody> },
    TContext
  >
  request?: SecondParameter<typeof customInstance>
}): UseMutationResult<
  TData,
  TError,
  { data: BodyType<FilesControllerUploadFileBody> },
  TContext
> => {
  const mutationOptions = getFilesControllerUploadFileMutationOptions(options)

  return useMutation(mutationOptions)
}
/**
 * Downloads the specified file.
 * @summary Download File
 */
export const filesControllerDownload = (
  fileName: string,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal
) => {
  return customInstance<unknown>(
    { url: `/api/v1/files/${fileName}`, method: 'GET', signal },
    options
  )
}

export const getFilesControllerDownloadQueryKey = (fileName: string) => {
  return [`/api/v1/files/${fileName}`] as const
}

export const getFilesControllerDownloadQueryOptions = <
  TData = Awaited<ReturnType<typeof filesControllerDownload>>,
  TError = ErrorType<void>,
>(
  fileName: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof filesControllerDownload>>, TError, TData>
    >
    request?: SecondParameter<typeof customInstance>
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getFilesControllerDownloadQueryKey(fileName)

  const queryFn: QueryFunction<Awaited<ReturnType<typeof filesControllerDownload>>> = ({
    signal,
  }) => filesControllerDownload(fileName, requestOptions, signal)

  return { queryKey, queryFn, enabled: !!fileName, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof filesControllerDownload>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type FilesControllerDownloadQueryResult = NonNullable<
  Awaited<ReturnType<typeof filesControllerDownload>>
>
export type FilesControllerDownloadQueryError = ErrorType<void>

export function useFilesControllerDownload<
  TData = Awaited<ReturnType<typeof filesControllerDownload>>,
  TError = ErrorType<void>,
>(
  fileName: string,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof filesControllerDownload>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof filesControllerDownload>>,
          TError,
          TData
        >,
        'initialData'
      >
    request?: SecondParameter<typeof customInstance>
  }
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useFilesControllerDownload<
  TData = Awaited<ReturnType<typeof filesControllerDownload>>,
  TError = ErrorType<void>,
>(
  fileName: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof filesControllerDownload>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof filesControllerDownload>>,
          TError,
          TData
        >,
        'initialData'
      >
    request?: SecondParameter<typeof customInstance>
  }
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useFilesControllerDownload<
  TData = Awaited<ReturnType<typeof filesControllerDownload>>,
  TError = ErrorType<void>,
>(
  fileName: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof filesControllerDownload>>, TError, TData>
    >
    request?: SecondParameter<typeof customInstance>
  }
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Download File
 */

export function useFilesControllerDownload<
  TData = Awaited<ReturnType<typeof filesControllerDownload>>,
  TError = ErrorType<void>,
>(
  fileName: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof filesControllerDownload>>, TError, TData>
    >
    request?: SecondParameter<typeof customInstance>
  }
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getFilesControllerDownloadQueryOptions(fileName, options)

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
  }

  query.queryKey = queryOptions.queryKey

  return query
}

/**
 * Deletes the specified file.
 * @summary Delete File
 */
export const filesControllerDeleteFile = (
  fileName: string,
  options?: SecondParameter<typeof customInstance>
) => {
  return customInstance<unknown>({ url: `/api/v1/files/${fileName}`, method: 'DELETE' }, options)
}

export const getFilesControllerDeleteFileMutationOptions = <
  TData = Awaited<ReturnType<typeof filesControllerDeleteFile>>,
  TError = ErrorType<void>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<TData, TError, { fileName: string }, TContext>
  request?: SecondParameter<typeof customInstance>
}) => {
  const mutationKey = ['filesControllerDeleteFile']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof filesControllerDeleteFile>>,
    { fileName: string }
  > = (props) => {
    const { fileName } = props ?? {}

    return filesControllerDeleteFile(fileName, requestOptions)
  }

  return { mutationFn, ...mutationOptions } as UseMutationOptions<
    TData,
    TError,
    { fileName: string },
    TContext
  >
}

export type FilesControllerDeleteFileMutationResult = NonNullable<
  Awaited<ReturnType<typeof filesControllerDeleteFile>>
>

export type FilesControllerDeleteFileMutationError = ErrorType<void>

/**
 * @summary Delete File
 */
export const useFilesControllerDeleteFile = <
  TData = Awaited<ReturnType<typeof filesControllerDeleteFile>>,
  TError = ErrorType<void>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<TData, TError, { fileName: string }, TContext>
  request?: SecondParameter<typeof customInstance>
}): UseMutationResult<TData, TError, { fileName: string }, TContext> => {
  const mutationOptions = getFilesControllerDeleteFileMutationOptions(options)

  return useMutation(mutationOptions)
}
