/* eslint-disable @typescript-eslint/no-explicit-any */
/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API
 * API documentation for the starter-kit project in NestJS by BinarApps. The API allows management of users, sessions and offers various functions for logged in users. Contains examples of authentication, authorization, and CRUD for selected resources.
 * OpenAPI spec version: 1.0
 */
import { faker } from '@faker-js/faker'
import { HttpResponse, delay, http } from 'msw'

import type { FileEntity } from '../../types'

export const getFilesControllerUploadFileResponseMock = (
  overrideResponse: any = {}
): FileEntity => ({
  category: faker.helpers.arrayElement([faker.word.sample(), null]),
  createdAt: `${faker.date.past().toISOString().split('.')[0]}Z`,
  id: faker.word.sample(),
  mimeType: faker.word.sample(),
  name: faker.word.sample(),
  path: faker.word.sample(),
  size: faker.number.int({ min: undefined, max: undefined }),
  userId: faker.word.sample(),
  ...overrideResponse,
})

export const getFilesControllerUploadFileMockHandler = (overrideResponse?: FileEntity) => {
  return http.post('/api/v1/files/upload', async () => {
    await delay(1000)
    return new HttpResponse(
      JSON.stringify(
        overrideResponse ? overrideResponse : getFilesControllerUploadFileResponseMock()
      ),
      {
        status: 200,
        headers: {
          'Content-Type': 'application/json',
        },
      }
    )
  })
}

export const getFilesControllerDownloadMockHandler = () => {
  return http.get('/api/v1/files/:fileName', async () => {
    await delay(1000)
    return new HttpResponse(null, {
      status: 200,
      headers: {
        'Content-Type': 'application/json',
      },
    })
  })
}

export const getFilesControllerDeleteFileMockHandler = () => {
  return http.delete('/api/v1/files/:fileName', async () => {
    await delay(1000)
    return new HttpResponse(null, {
      status: 200,
      headers: {
        'Content-Type': 'application/json',
      },
    })
  })
}
export const getFilesMock = () => [
  getFilesControllerUploadFileMockHandler(),
  getFilesControllerDownloadMockHandler(),
  getFilesControllerDeleteFileMockHandler(),
]
