appId: ${APP_ID}
tags:
  - settings
---
- assertVisible: 'light'
- tapOn: 'light'
- assertVisible: 'dark'
- tapOn: 'dark'
- assertVisible: 'system'
- tapOn: 'system'
- assertVisible: 'Sign out!'
- tapOn: 'Sign out!'
- assertVisible: 'Welcome back'
- assertVisible: 'Remember me'
- tapOn:
    text: 'Remember me'
- assertVisible: 'Log in'
- tapOn: 'Log in'
- assertVisible: 'Home'
- assertVisible: ' Profile'
- tapOn: ' Profile'
