flows:
  - 'auth/*'
  - 'home/*'
  - 'settings/*'
  - 'profile/*'

includeTags:
  - 'auth'
  - 'home'
  - 'settings'
  - 'profile'

executionOrder:
  continueOnFailure: false
  flowsOrder:
    - 'logout-when-needed'
    - 'login-with-validation'
    - 'details'
    - 'full-screen-form'
    - 'settings'
    # https://github.com/mobile-dev-inc/maestro/issues/1484
    # Wait for it to be resolved and then remove blog from the list
    # blog is not implemented, it's just a placeholder, to make tests run
    - 'blog'
    - 'profile'
