flows:
  - 'auth/*'
  - 'home/*'
  - 'categories/*'
  - 'example/*'
  - 'settings/*'
  - 'profile/*'

includeTags:
  - 'example'
  - 'auth'
  - 'home'
  - 'categories'
  - 'settings'
  - 'profile'

# excludeTags:
#   - 'utils'

executionOrder:
  continueOnFailure: true
  flowsOrder:
    - 'logout-when-needed'
    - 'login-with-validation'
    - 'details'
    - 'full-screen-form'
    - 'blog'
    - 'categories'
    - 'application-info'
    - 'colors'
    - 'components'
    - 'typography'
    # https://github.com/mobile-dev-inc/maestro/issues/1484
    # Wait for it to be resolved and then uncomment the line below
    # - 'homestack'
    - 'data-backend'
    - 'test-form'
    - 'notifications-helpers'
    - 'user-session'
    - 'settings'
    - 'profile'
